# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Dev Build and Lint

on:
  push:
    branches: ['master', 'development']
  pull_request:
    branches: ['master', 'development']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          check-latest: true
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build --if-present
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Format
        run: npm run prettier:format

      - name: Run Prettier Check
        run: npm run prettier:check
