name: Lint and Format

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Format
        run: npm run prettier:format

      - name: Run Prettier Check
        run: npm run prettier:check
